const products = [
  {
    id: 1,
    name: "Guitar Strap",
    price: 50,
    description: "Comfortable and adjustable strap for your guitar.",
    type: "accessory",
    image: "src/assets/guitar-strap.jpg",
  },
  {
    id: 2,
    name: "Guitar Picks",
    price: 5,
    description: "Set of assorted guitar picks for different playing styles.",
    type: "accessory",
    image: "src/assets/guitar-picks.jpg",
  },
  {
    id: 3,
    name: "Guitar Tuner",
    price: 30,
    description: "Easy-to-use tuner for keeping your guitar in tune.",
    type: "accessory",
    image: "src/assets/guitar-tuner.jpg",
  },
  {
    id: 4,
    name: "Martin D-28",
    price: 3200,
    description: "Classic acoustic dreadnought with rich tone.",
    type: "acoustic",
    image: "src/assets/martin-d28.jpg",
  },
  {
    id: 5,
    name: "Taylor 814ce",
    price: 3500,
    description: "Premium acoustic-electric with a balanced sound.",
    type: "acoustic",
    image: "src/assets/taylor-814ce.jpg",
  },
  {
    id: 6,
    name: "Gibson J-45",
    price: 3400,
    description: "Iconic acoustic with warm and full-bodied tone.",
    type: "acoustic",
    image: "src/assets/gibson-j45.jpg",
  },
  {
    id: 7,
    name: "Fender Stratocaster",
    price: 1500,
    description: "Versatile electric guitar with a signature sound.",
    type: "electric",
    image: "src/assets/fender-stratocaster.jpg",
  },
  {
    id: 8,
    name: "Gibson Les Paul",
    price: 2500,
    description: "Timeless electric guitar known for its sustain.",
    type: "electric",
    image: "src/assets/gibson-les-paul.jpg",
  },
  {
    id: 9,
    name: "Ibanez RG550",
    price: 1200,
    description: "Fast and high-performance electric guitar.",
    type: "electric",
    image: "src/assets/ibanez-rg550.jpg",
  },
];

export default products;
